name: basic_m6502_dart
description: A Dart implementation of Microsoft BASIC 1.1 for 6502, originally written for Commodore PET, Apple II, and other early microcomputers.
version: 1.0.0
repository: https://github.com/dsyrstad/BASIC-M6502

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
